export enum internalErrorCodes {
  INTERNAL_ERROR = "INTERNAL_ERROR",
  GENERIC_ERROR = "GENERIC_ERROR",
  SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT_ERROR = "CONFLICT_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
  FORBIDDEN_ERROR = "FORBIDDEN_ERROR",
}
